name: "Build Android APK"

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  android-build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Accept Android Licenses
        run: |
          echo y | "%ANDROID_SDK_ROOT%\cmdline-tools\latest\bin\sdkmanager.bat" --licenses
        shell: cmd

      - name: Install Required Android SDKs
        run: |
          "%ANDROID_SDK_ROOT%\cmdline-tools\latest\bin\sdkmanager.bat" "platforms;android-33" "build-tools;33.0.0" "ndk;21.4.7075529"
        shell: cmd

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build APK (split per ABI)
        run: flutter build apk --release --split-per-abi -v

      - name: Upload APKs to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/*.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
