name: "Build Android APK"

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  android-build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build APK (Verbose Output)
        run: flutter build apk --release --split-per-abi -v
