name: "Build Android APK"

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  android-build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'  # Safer than 12

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APKs to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/*.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
